```plantuml
@startuml API
app -- tge.runtime : use
app : Create(settings Settings) error
app : Start(runtime Runtime) error
app : Resize(width int, height int) error
app : Resume() error
app : Pause() error
app : Dispose() error

tge.runtime *-- tge.context
tge.runtime : GetContext() Context
tge.runtime : GetUI() UI
tge.runtime : GetPhysics() Physics
tge.runtime : GetSound() Sound

tge.runtime *-- tge.ui
tge.runtime *-- tge.physics
tge.runtime *-- tge.sound
@enduml
```