```plantuml
@startuml API
' Components
interface App {
    OnCreate(Settings) error
    OnStart(Runtime) error
    OnResume()
    OnRender(Duration, <-chan interface{})
    OnTick(Duration, chan<- interface{})
    OnPause()
    OnStop()
    OnDispose()
}

class tge << (P,#FF7700) Package >> {
    {static} Register(Plugin)
    {static} Run(App)
}

class "tge-{plugin}" << (P,#FF7700) Package >> {
}

interface Runtime {
    GetAsset(string) []byte, error
    GetHost() interface{}
    GetRenderer() interface{}
    GetSettings() Settings
    Subscribe(string, Listener)
	Unsubscribe(string, Listener)
    Publish(Event)
    Stop()
}

interface Plugin{    
    Init(Runtime) error
    GetName() string
    Dispose()
}

' Relations
App ..> tge : import
App ..> "tge-{plugin}" : import

App <-- Runtime : manage
App --> Runtime : use
tge --> Runtime : instanciate

Runtime --> Plugin : manage
Plugin --> Runtime  : use
"tge-{plugin}" --> Plugin : instanciate

@enduml
```