```plantuml
@startuml API
' Components
interface App {
    OnCreate(*Settings) error
    OnStart(Runtime) error
    OnResize(int, int)
    OnResume()
    OnRender(Renderer, UI, Player)
    OnTick(Physics)
    OnPause()
    OnStop()
    OnDispose()
}

class tge << (P,#FF7700) Package >> {
    {static} Run(App, *Settings) error
}

interface Runtime {
    Stop()
}

interface Renderer {
}

interface UI {
}

interface Player {
}

interface Physics {
}

' Relations
App --> tge : call
tge --> Runtime : instanciate
App <-- Runtime : use

Runtime *-- Renderer
Runtime *-- UI
Runtime *-- Player
Runtime *-- Physics
@enduml
```