```plantuml
@startuml Browser Implementation
class tge << (P,#FF7700) Package >>
tge <|-- "syscall.js"

class "tge-gl" << (P,#FF7700) Package >>
"tge-gl" <|-- "syscall.js"

interface Renderer
Renderer <|-- "syscall.js.Value"

@enduml
```